# Generated by Django 5.2.7 on 2025-10-17 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Forum",
                "verbose_name_plural": "Forums",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=210, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="thread",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="thread",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Thread",
                "verbose_name_plural": "Threads",
            },
        ),
        migrations.RenameField(
            model_name="thread",
            old_name="starter",
            new_name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="is_edit",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="locked",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="thread",
            name="views",
        ),
        migrations.AddField(
            model_name="thread",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="thread",
            name="forum",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="forum.forum",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="forum",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forums",
                to="forum.subject",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
